# Generated by Django 2.1.7 on 2020-02-13 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.UUID('a3c9b1e0-3604-4fec-93cb-4962808272e5'), editable=False, primary_key=True, serialize=False, verbose_name='id_news')),
                ('context', models.TextField(verbose_name='news_context')),
                ('reply', models.BooleanField(default=False, verbose_name='is_reply')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('liked', models.ManyToManyField(blank=True, null=True, related_name='liked_news', to=settings.AUTH_USER_MODEL, verbose_name='news_liked_user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='news.News', verbose_name='self_parent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'home',
                'ordering': ('-created_at',),
            },
        ),
    ]
