# Generated by Django 2.1.7 on 2020-02-23 10:55

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='liked',
            field=models.ManyToManyField(related_name='liked_news', to=settings.AUTH_USER_MODEL, verbose_name='news_liked_user'),
        ),
        migrations.AlterField(
            model_name='news',
            name='uuid_id',
            field=models.UUIDField(default=uuid.UUID('d3e07d91-f396-44e2-83ba-45e633fa4377'), editable=False, primary_key=True, serialize=False, verbose_name='id_news'),
        ),
    ]
