# Generated by Django 2.1.7 on 2020-02-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200223_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='context',
            new_name='content',
        ),
    ]
